var files_dup =
[
    [ "arial_fonts.c", "arial__fonts_8c.html", "arial__fonts_8c" ],
    [ "arial_fonts.h", "arial__fonts_8h.html", "arial__fonts_8h" ],
    [ "bitmaps.c", "bitmaps_8c.html", "bitmaps_8c" ],
    [ "bitmaps.h", "bitmaps_8h.html", "bitmaps_8h" ],
    [ "consolas_fonts.c", "consolas__fonts_8c.html", "consolas__fonts_8c" ],
    [ "consolas_fonts.h", "consolas__fonts_8h.html", "consolas__fonts_8h" ],
    [ "dma.c", "dma_8c.html", "dma_8c" ],
    [ "dma.h", "dma_8h.html", "dma_8h" ],
    [ "FL.c", "_f_l_8c.html", "_f_l_8c" ],
    [ "FL.h", "_f_l_8h.html", "_f_l_8h" ],
    [ "gpio.c", "gpio_8c.html", "gpio_8c" ],
    [ "gpio.h", "gpio_8h.html", "gpio_8h" ],
    [ "IOL.c", "_i_o_l_8c.html", "_i_o_l_8c" ],
    [ "IOL.h", "_i_o_l_8h.html", "_i_o_l_8h" ],
    [ "LL.c", "_l_l_8c.html", "_l_l_8c" ],
    [ "LL.h", "_l_l_8h.html", "_l_l_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "main.h", "main_8h.html", "main_8h" ],
    [ "stm32_ub_vga_screen.c", "stm32__ub__vga__screen_8c.html", "stm32__ub__vga__screen_8c" ],
    [ "stm32_ub_vga_screen.h", "stm32__ub__vga__screen_8h.html", "stm32__ub__vga__screen_8h" ],
    [ "stm32f4xx_hal_conf.h", "stm32f4xx__hal__conf_8h.html", "stm32f4xx__hal__conf_8h" ],
    [ "stm32f4xx_hal_msp.c", "stm32f4xx__hal__msp_8c.html", "stm32f4xx__hal__msp_8c" ],
    [ "stm32f4xx_it.c", "stm32f4xx__it_8c.html", "stm32f4xx__it_8c" ],
    [ "stm32f4xx_it.h", "stm32f4xx__it_8h.html", "stm32f4xx__it_8h" ],
    [ "syscalls.c", "syscalls_8c.html", "syscalls_8c" ],
    [ "sysmem.c", "sysmem_8c.html", "sysmem_8c" ],
    [ "system_stm32f4xx.c", "system__stm32f4xx_8c.html", "system__stm32f4xx_8c" ],
    [ "Tetris.c", "_tetris_8c.html", "_tetris_8c" ],
    [ "Tetris.h", "_tetris_8h.html", null ],
    [ "tim.c", "tim_8c.html", "tim_8c" ],
    [ "tim.h", "tim_8h.html", "tim_8h" ],
    [ "usart.c", "usart_8c.html", "usart_8c" ],
    [ "usart.h", "usart_8h.html", "usart_8h" ]
];